/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls
    /// </summary>
    [DataContract(Name = "_prod_mobile_ecomm_products_PNS__store_guid__search_q__term__post_200_response_products_inner_productImageUrls")]
    public partial class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls" /> class.
        /// </summary>
        /// <param name="var100">var100.</param>
        /// <param name="var200">var200.</param>
        /// <param name="var400">var400.</param>
        /// <param name="var500">var500.</param>
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls(string var100 = default(string), string var200 = default(string), string var400 = default(string), string var500 = default(string))
        {
            this.Var100 = var100;
            this.Var200 = var200;
            this.Var400 = var400;
            this.Var500 = var500;
        }

        /// <summary>
        /// Gets or Sets Var100
        /// </summary>
        [DataMember(Name = "100", EmitDefaultValue = false)]
        public string Var100 { get; set; }

        /// <summary>
        /// Gets or Sets Var200
        /// </summary>
        [DataMember(Name = "200", EmitDefaultValue = false)]
        public string Var200 { get; set; }

        /// <summary>
        /// Gets or Sets Var400
        /// </summary>
        [DataMember(Name = "400", EmitDefaultValue = false)]
        public string Var400 { get; set; }

        /// <summary>
        /// Gets or Sets Var500
        /// </summary>
        [DataMember(Name = "500", EmitDefaultValue = false)]
        public string Var500 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls {\n");
            sb.Append("  Var100: ").Append(Var100).Append("\n");
            sb.Append("  Var200: ").Append(Var200).Append("\n");
            sb.Append("  Var400: ").Append(Var400).Append("\n");
            sb.Append("  Var500: ").Append(Var500).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
