/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories
    /// </summary>
    [DataContract(Name = "_prod_mobile_ecomm_products_PNS__store_guid__search_q__term__post_200_response_filters_Categories")]
    public partial class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories" /> class.
        /// </summary>
        /// <param name="cakesMuffins">cakesMuffins.</param>
        /// <param name="freshCakesMuffins">freshCakesMuffins.</param>
        /// <param name="giftIdeasForMum">giftIdeasForMum.</param>
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories(int cakesMuffins = default(int), int freshCakesMuffins = default(int), int giftIdeasForMum = default(int))
        {
            this.CakesMuffins = cakesMuffins;
            this.FreshCakesMuffins = freshCakesMuffins;
            this.GiftIdeasForMum = giftIdeasForMum;
        }

        /// <summary>
        /// Gets or Sets CakesMuffins
        /// </summary>
        [DataMember(Name = "Cakes &amp; Muffins", EmitDefaultValue = false)]
        public int CakesMuffins { get; set; }

        /// <summary>
        /// Gets or Sets FreshCakesMuffins
        /// </summary>
        [DataMember(Name = "Fresh Cakes &amp; Muffins", EmitDefaultValue = false)]
        public int FreshCakesMuffins { get; set; }

        /// <summary>
        /// Gets or Sets GiftIdeasForMum
        /// </summary>
        [DataMember(Name = "Gift Ideas for Mum", EmitDefaultValue = false)]
        public int GiftIdeasForMum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories {\n");
            sb.Append("  CakesMuffins: ").Append(CakesMuffins).Append("\n");
            sb.Append("  FreshCakesMuffins: ").Append(FreshCakesMuffins).Append("\n");
            sb.Append("  GiftIdeasForMum: ").Append(GiftIdeasForMum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
