/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters
    /// </summary>
    [DataContract(Name = "_prod_mobile_ecomm_products_PNS__store_guid__search_q__term__post_200_response_filters")]
    public partial class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters" /> class.
        /// </summary>
        /// <param name="deals">deals.</param>
        /// <param name="dietaryLifestyle">dietaryLifestyle.</param>
        /// <param name="categories">categories.</param>
        /// <param name="brands">brands.</param>
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters(ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals deals = default(ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals), ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle dietaryLifestyle = default(ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle), ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories categories = default(ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories), ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersBrands brands = default(ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersBrands))
        {
            this.Deals = deals;
            this.DietaryLifestyle = dietaryLifestyle;
            this.Categories = categories;
            this.Brands = brands;
        }

        /// <summary>
        /// Gets or Sets Deals
        /// </summary>
        [DataMember(Name = "Deals", EmitDefaultValue = false)]
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals Deals { get; set; }

        /// <summary>
        /// Gets or Sets DietaryLifestyle
        /// </summary>
        [DataMember(Name = "Dietary &amp; lifestyle", EmitDefaultValue = false)]
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle DietaryLifestyle { get; set; }

        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [DataMember(Name = "Categories", EmitDefaultValue = false)]
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories Categories { get; set; }

        /// <summary>
        /// Gets or Sets Brands
        /// </summary>
        [DataMember(Name = "Brands", EmitDefaultValue = false)]
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersBrands Brands { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters {\n");
            sb.Append("  Deals: ").Append(Deals).Append("\n");
            sb.Append("  DietaryLifestyle: ").Append(DietaryLifestyle).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Brands: ").Append(Brands).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
