/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShopApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search for Items in Shop
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response</returns>
        ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response ProdMobileEcommProductsPNSStoreGuidSearchqtermPost(Guid storeGuid, string term, int operationIndex = 0);

        /// <summary>
        /// Search for Items in Shop
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response</returns>
        ApiResponse<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response> ProdMobileEcommProductsPNSStoreGuidSearchqtermPostWithHttpInfo(Guid storeGuid, string term, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShopApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Search for Items in Shop
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response</returns>
        System.Threading.Tasks.Task<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response> ProdMobileEcommProductsPNSStoreGuidSearchqtermPostAsync(Guid storeGuid, string term, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Search for Items in Shop
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response>> ProdMobileEcommProductsPNSStoreGuidSearchqtermPostWithHttpInfoAsync(Guid storeGuid, string term, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShopApi : IShopApiSync, IShopApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ShopApi : IShopApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ShopApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ShopApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ShopApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ShopApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Search for Items in Shop 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response</returns>
        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response ProdMobileEcommProductsPNSStoreGuidSearchqtermPost(Guid storeGuid, string term, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response> localVarResponse = ProdMobileEcommProductsPNSStoreGuidSearchqtermPostWithHttpInfo(storeGuid, term);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search for Items in Shop 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response</returns>
        public Org.OpenAPITools.Client.ApiResponse<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response> ProdMobileEcommProductsPNSStoreGuidSearchqtermPostWithHttpInfo(Guid storeGuid, string term, int operationIndex = 0)
        {
            // verify the required parameter 'term' is set
            if (term == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'term' when calling ShopApi->ProdMobileEcommProductsPNSStoreGuidSearchqtermPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("store-guid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(storeGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("term", Org.OpenAPITools.Client.ClientUtils.ParameterToString(term)); // path parameter

            localVarRequestOptions.Operation = "ShopApi.ProdMobileEcommProductsPNSStoreGuidSearchqtermPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response>("/prod/mobile/ecomm-products/PNS/{store-guid}/search?q={term}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProdMobileEcommProductsPNSStoreGuidSearchqtermPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Search for Items in Shop 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response</returns>
        public async System.Threading.Tasks.Task<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response> ProdMobileEcommProductsPNSStoreGuidSearchqtermPostAsync(Guid storeGuid, string term, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response> localVarResponse = await ProdMobileEcommProductsPNSStoreGuidSearchqtermPostWithHttpInfoAsync(storeGuid, term, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Search for Items in Shop 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeGuid">The Store GUID you&#39;re searching on.</param>
        /// <param name="term">The item you&#39;re searching for</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response>> ProdMobileEcommProductsPNSStoreGuidSearchqtermPostWithHttpInfoAsync(Guid storeGuid, string term, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'term' is set
            if (term == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'term' when calling ShopApi->ProdMobileEcommProductsPNSStoreGuidSearchqtermPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("store-guid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(storeGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("term", Org.OpenAPITools.Client.ClientUtils.ParameterToString(term)); // path parameter

            localVarRequestOptions.Operation = "ShopApi.ProdMobileEcommProductsPNSStoreGuidSearchqtermPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response>("/prod/mobile/ecomm-products/PNS/{store-guid}/search?q={term}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProdMobileEcommProductsPNSStoreGuidSearchqtermPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
