/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetCurrentUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCurrentUserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetCurrentUserResponse
        //private GetCurrentUserResponse instance;

        public GetCurrentUserResponseTests()
        {
            // TODO uncomment below to create an instance of GetCurrentUserResponse
            //instance = new GetCurrentUserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetCurrentUserResponse
        /// </summary>
        [Fact]
        public void GetCurrentUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetCurrentUserResponse
            //Assert.IsType<GetCurrentUserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'ExpiresTime'
        /// </summary>
        [Fact]
        public void ExpiresTimeTest()
        {
            // TODO unit test for the property 'ExpiresTime'
        }

        /// <summary>
        /// Test the property 'CurrentTime'
        /// </summary>
        [Fact]
        public void CurrentTimeTest()
        {
            // TODO unit test for the property 'CurrentTime'
        }

        /// <summary>
        /// Test the property 'HasClubCard'
        /// </summary>
        [Fact]
        public void HasClubCardTest()
        {
            // TODO unit test for the property 'HasClubCard'
        }
    }
}
