/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyleTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyleInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDietaryLifestyle>(instance);
        }

        /// <summary>
        /// Test the property 'NonGMO'
        /// </summary>
        [Fact]
        public void NonGMOTest()
        {
            // TODO unit test for the property 'NonGMO'
        }
    }
}
