/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInner>(instance);
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }

        /// <summary>
        /// Test the property 'ProductImageUrls'
        /// </summary>
        [Fact]
        public void ProductImageUrlsTest()
        {
            // TODO unit test for the property 'ProductImageUrls'
        }

        /// <summary>
        /// Test the property 'AvailableInStore'
        /// </summary>
        [Fact]
        public void AvailableInStoreTest()
        {
            // TODO unit test for the property 'AvailableInStore'
        }

        /// <summary>
        /// Test the property 'AvailableInOnline'
        /// </summary>
        [Fact]
        public void AvailableInOnlineTest()
        {
            // TODO unit test for the property 'AvailableInOnline'
        }

        /// <summary>
        /// Test the property 'TobaccoFlag'
        /// </summary>
        [Fact]
        public void TobaccoFlagTest()
        {
            // TODO unit test for the property 'TobaccoFlag'
        }

        /// <summary>
        /// Test the property 'LiquorFlag'
        /// </summary>
        [Fact]
        public void LiquorFlagTest()
        {
            // TODO unit test for the property 'LiquorFlag'
        }

        /// <summary>
        /// Test the property 'SaleType'
        /// </summary>
        [Fact]
        public void SaleTypeTest()
        {
            // TODO unit test for the property 'SaleType'
        }
    }
}
