/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFilters>(instance);
        }

        /// <summary>
        /// Test the property 'Deals'
        /// </summary>
        [Fact]
        public void DealsTest()
        {
            // TODO unit test for the property 'Deals'
        }

        /// <summary>
        /// Test the property 'DietaryLifestyle'
        /// </summary>
        [Fact]
        public void DietaryLifestyleTest()
        {
            // TODO unit test for the property 'DietaryLifestyle'
        }

        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }

        /// <summary>
        /// Test the property 'Brands'
        /// </summary>
        [Fact]
        public void BrandsTest()
        {
            // TODO unit test for the property 'Brands'
        }
    }
}
