/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrlsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrlsTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrlsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseProductsInnerProductImageUrls>(instance);
        }

        /// <summary>
        /// Test the property 'Var100'
        /// </summary>
        [Fact]
        public void Var100Test()
        {
            // TODO unit test for the property 'Var100'
        }

        /// <summary>
        /// Test the property 'Var200'
        /// </summary>
        [Fact]
        public void Var200Test()
        {
            // TODO unit test for the property 'Var200'
        }

        /// <summary>
        /// Test the property 'Var400'
        /// </summary>
        [Fact]
        public void Var400Test()
        {
            // TODO unit test for the property 'Var400'
        }

        /// <summary>
        /// Test the property 'Var500'
        /// </summary>
        [Fact]
        public void Var500Test()
        {
            // TODO unit test for the property 'Var500'
        }
    }
}
