/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200Response>(instance);
        }

        /// <summary>
        /// Test the property 'TobaccoFiltered'
        /// </summary>
        [Fact]
        public void TobaccoFilteredTest()
        {
            // TODO unit test for the property 'TobaccoFiltered'
        }

        /// <summary>
        /// Test the property 'TotalHits'
        /// </summary>
        [Fact]
        public void TotalHitsTest()
        {
            // TODO unit test for the property 'TotalHits'
        }

        /// <summary>
        /// Test the property 'HitsPerPage'
        /// </summary>
        [Fact]
        public void HitsPerPageTest()
        {
            // TODO unit test for the property 'HitsPerPage'
        }

        /// <summary>
        /// Test the property 'NumberOfPages'
        /// </summary>
        [Fact]
        public void NumberOfPagesTest()
        {
            // TODO unit test for the property 'NumberOfPages'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
    }
}
