/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDealsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDealsTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDealsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersDeals>(instance);
        }

        /// <summary>
        /// Test the property 'Deals'
        /// </summary>
        [Fact]
        public void DealsTest()
        {
            // TODO unit test for the property 'Deals'
        }
    }
}
