/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileV1ErrorGet200ResponseValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileV1ErrorGet200ResponseValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileV1ErrorGet200ResponseValue
        //private ProdMobileV1ErrorGet200ResponseValue instance;

        public ProdMobileV1ErrorGet200ResponseValueTests()
        {
            // TODO uncomment below to create an instance of ProdMobileV1ErrorGet200ResponseValue
            //instance = new ProdMobileV1ErrorGet200ResponseValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileV1ErrorGet200ResponseValue
        /// </summary>
        [Fact]
        public void ProdMobileV1ErrorGet200ResponseValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileV1ErrorGet200ResponseValue
            //Assert.IsType<ProdMobileV1ErrorGet200ResponseValue>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
    }
}
