/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategoriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories
        //private ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories instance;

        public ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategoriesTests()
        {
            // TODO uncomment below to create an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories
            //instance = new ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories
        /// </summary>
        [Fact]
        public void ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategoriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories
            //Assert.IsType<ProdMobileEcommProductsPNSStoreGuidSearchQTermPost200ResponseFiltersCategories>(instance);
        }

        /// <summary>
        /// Test the property 'CakesMuffins'
        /// </summary>
        [Fact]
        public void CakesMuffinsTest()
        {
            // TODO unit test for the property 'CakesMuffins'
        }

        /// <summary>
        /// Test the property 'FreshCakesMuffins'
        /// </summary>
        [Fact]
        public void FreshCakesMuffinsTest()
        {
            // TODO unit test for the property 'FreshCakesMuffins'
        }

        /// <summary>
        /// Test the property 'GiftIdeasForMum'
        /// </summary>
        [Fact]
        public void GiftIdeasForMumTest()
        {
            // TODO unit test for the property 'GiftIdeasForMum'
        }
    }
}
