/*
 * Foodstuffs API - Pak 'n Save & New World
 *
 * Foodstuffs API, providing access to Pak'nSave and New World stores without using their website or mobile app.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LocaleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LocaleApiTests : IDisposable
    {
        private LocaleApi instance;

        public LocaleApiTests()
        {
            instance = new LocaleApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocaleApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LocaleApi
            //Assert.IsType<LocaleApi>(instance);
        }

        /// <summary>
        /// Test ProdMobileV1ErrorGet
        /// </summary>
        [Fact]
        public void ProdMobileV1ErrorGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ProdMobileV1ErrorGet();
            //Assert.IsType<Dictionary<string, ProdMobileV1ErrorGet200ResponseValue>>(response);
        }
    }
}
